/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.arkane.template;

import java.util.HashMap;
import java.util.Map;
import spark.Request;
import spark.Response;
import spark.ModelAndView;
import spark.TemplateEngine,
import static spark.Spark.get;
import static spark.Spark.staticFileLocation;

public class SparkApp {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new SparkApp().getGreeting());
        get("/first", (req, res) -> "First Spark application");    
        get("/hello/:name", (req, res)->"Hello " + req.params(":name"));
    }
}
