/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.arkane.sparkapp;

//import sparkapp.resources;
import static spark.Spark.get;

public class SparkApp {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new SparkApp().getGreeting());
        get("/first", (req, res) -> "First Spark application");    
//        get("/hello/:name", (req, res)->"Hello " + req.params(":name"));
    }
}
