/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.arkane.sparkapp.SparkApp;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        SparkApp classUnderTest = new SparkApp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
